### ISSUE TITLE
package.json でバージョンを固定しても、upgrade 対象とされてしまう

### ISSUE THREAD

**Issue by mori-dev** [taichi/ci-yarn-upgrade#19]
package.json でバージョンを固定しても、upgrade 対象とされてしまう。そのため、バージョンを固定して利用したいライブラリまで含めたプルリクエストが作成されてしまう。

例です。

```
  "dependencies": {
    "react-swipeable-views": "0.10.5",
  }
```

### 参考URL

- https://docs.npmjs.com/files/package.json#dependencies

**Comment by taichi** [comment]
以下のようなプロジェクトを作ってみましたが、僕の環境では状況が再現しません。

* https://gist.github.com/taichi/e874191e146b87a0287f75ad8699ec79

このプロジェクトに対して、`ci-yarn-upgrade` を実行してもプルリクエストは作成されません。

どのような状況なのか、もう少し詳しく説明して頂けないでしょうか？

**Comment by mori-dev** [comment]
古い yarn.lock のまま、commit, push, pull request すると発生していました。
yarn.lock を削除し、yarn install し直すと、ci からの パッケージアップデートの pull request は発生しませんでした。

以下は補足です。

- pull request は、GitHub の Setting から Default branch を development ブランチにすることで、 master ブランチではなく development ブランチに対して行っています。
- yarn.lock, circle.yml, package.json は https://gist.github.com/mori-dev/c0557240e001bcba2b46b872e32c87cd です。

- CircleCI の GUI に表示されたログです。

```
ci-yarn-upgrade --verbose --execute

> BEGIN yarnpkg install
> END   yarnpkg install
> BEGIN yarnpkg outdated
> END   yarnpkg outdated
> Find some outdated dependencies.
> difference table {"type":"table","data":{"head":["Package","Current","Wanted","Latest","Package Type"],"body":[["react-swipeable-views","0.10.5","0.10.5","0.10.8","dependencies"],["eslint-config-airbnb","13.0.0","13.0.0","14.1.0","devDependencies"],["eslint-plugin-jsx-a11y","2.2.3","2.2.3","4.0.0","devDependencies"]]}}
> Did not find outdated dependencies.
dependencies are not up to date.
```

お騒がせしました。
