### ISSUE TITLE
v0.5.2 does not include PR #60

### ISSUE THREAD

**Issue by tsub** [taichi/ci-yarn-upgrade#62]
@taichi

Thank you for merging and releasing PR https://github.com/taichi/ci-yarn-upgrade/pull/60.

However, [v0.5.2](https://www.npmjs.com/package/ci-yarn-upgrade/v/0.5.2) distributed at npm does not include PR https://github.com/taichi/ci-yarn-upgrade/pull/60 changes :cry:

```
$ yarn add ci-yarn-upgrade
$ head -n32 node_modules/ci-yarn-upgrade/lib/compare.js | tail -n1
        return cw.homepage ? `[${cw.name}](${cw.homepage})` : cw.name;
```

**Comment by taichi** [comment]
oh... i'm sorry about release v0.5.2.

i release v0.5.3 again, please check it.
