### ISSUE TITLE
--latestフラグが設定された場合はpackage.jsonもプルリクエストの対象にしなくてもよい？

### ISSUE THREAD

**Issue by dim0627** [taichi/ci-yarn-upgrade#78]
こんにちは！
とても便利なツールを公開していただいてありがとうございます 😊 
僕の関わるほとんどのプロジェクトで導入させてもらっていて、とても助かってます！

1つ低レベルな質問をさせてください 🙇 
`--latest`フラグがtrueの場合、`package.json`はプルリクエストに含めなくてよいのかな？と気になっています。

> package.json は最新バージョンの範囲を反映したものに更新されます。 デフォルトでは、package.json で既存の範囲を指定する表現が、 ^、 ~、 &lt、 =、 > のいずれか、もしくは当該のバージョンであった場合は再利用されます。 それ以外の場合、キャレット (^) に変更されます。 フラグ --caret、 --tilde もしくは --exact のいずれかが範囲を明示的に指定するのに使用されます。
>
> https://yarnpkg.com/ja/docs/cli/upgrade#toc-yarn-upgrade-package-latest-l-caret-tilde-exact-pattern

`package.json`だけ古いと、手元にpullしてきたときに`yarn install`で差分が出てしまって困っております 💦 
もしなにか手順の誤り等があればご教示いただけると幸いです！

**Comment by taichi** [comment]
僕の考慮漏れですね。PRの内容は大変素晴らしいものです。ありがとうございます。
後で細かい確認をして問題なければ、頂いたPRを含んだ最新版をリリースしますので、少しだけお待ち下さい。

**Comment by dim0627** [comment]
良かったです 😊 
ありがとうございます！お手数ですが、よろしくおねがいします 🙇

**Comment by taichi** [comment]
0.6.2 として頂いたPRを含むバージョンをリリースしました。

**Comment by dim0627** [comment]
ありがとうございましたー！
